# Generated by Django 3.2.2 on 2023-09-22 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('e_commerce', '0002_userdata'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userdata',
            name='codigo_postal',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
