# Generated by Django 3.2.2 on 2023-10-20 18:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('e_commerce', '0003_alter_userdata_codigo_postal'),
    ]

    operations = [
        migrations.CreateModel(
            name='Compra',
            fields=[
                ('id', models.BigAutoField(db_column='ID', primary_key=True, serialize=False)),
                ('cantidad_total', models.PositiveIntegerField()),
                ('total_precio', models.DecimalField(decimal_places=2, max_digits=10)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'compra',
                'verbose_name_plural': 'compras',
                'db_table': 'e_commerce_compra',
            },
        ),
        migrations.CreateModel(
            name='ComicCompra',
            fields=[
                ('id', models.BigAutoField(db_column='ID', primary_key=True, serialize=False)),
                ('cantidad', models.PositiveIntegerField()),
                ('comic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='e_commerce.comic')),
                ('compra', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='e_commerce.compra')),
            ],
            options={
                'verbose_name': 'detalle compra',
                'verbose_name_plural': 'detalle compras',
                'db_table': 'e_commerce_comic_compra',
            },
        ),
    ]
